# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Patrick\Dokumente\Python Projects\CampbellControl\common\lib\clients\status_bar\status_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusBar(object):
    def setupUi(self, StatusBar):
        StatusBar.setObjectName("StatusBar")
        StatusBar.resize(787, 68)
        self.vbox_layout = QtWidgets.QVBoxLayout(StatusBar)
        self.vbox_layout.setObjectName("vbox_layout")
        self.hbox_layout0 = QtWidgets.QHBoxLayout()
        self.hbox_layout0.setObjectName("hbox_layout0")
        self.c00 = QtWidgets.QComboBox(StatusBar)
        self.c00.setObjectName("c00")
        self.hbox_layout0.addWidget(self.c00)
        self.c01 = QtWidgets.QComboBox(StatusBar)
        self.c01.setObjectName("c01")
        self.hbox_layout0.addWidget(self.c01)
        self.c02 = QtWidgets.QComboBox(StatusBar)
        self.c02.setObjectName("c02")
        self.hbox_layout0.addWidget(self.c02)
        self.c03 = QtWidgets.QComboBox(StatusBar)
        self.c03.setObjectName("c03")
        self.hbox_layout0.addWidget(self.c03)
        self.c04 = QtWidgets.QComboBox(StatusBar)
        self.c04.setObjectName("c04")
        self.hbox_layout0.addWidget(self.c04)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_layout0.addItem(spacerItem)
        self.vbox_layout.addLayout(self.hbox_layout0)
        self.hbox_layout1 = QtWidgets.QHBoxLayout()
        self.hbox_layout1.setObjectName("hbox_layout1")
        self.c10 = QtWidgets.QComboBox(StatusBar)
        self.c10.setObjectName("c10")
        self.hbox_layout1.addWidget(self.c10)
        self.c11 = QtWidgets.QComboBox(StatusBar)
        self.c11.setObjectName("c11")
        self.hbox_layout1.addWidget(self.c11)
        self.c12 = QtWidgets.QComboBox(StatusBar)
        self.c12.setObjectName("c12")
        self.hbox_layout1.addWidget(self.c12)
        self.c13 = QtWidgets.QComboBox(StatusBar)
        self.c13.setObjectName("c13")
        self.hbox_layout1.addWidget(self.c13)
        self.c14 = QtWidgets.QComboBox(StatusBar)
        self.c14.setObjectName("c14")
        self.hbox_layout1.addWidget(self.c14)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_layout1.addItem(spacerItem1)
        self.vbox_layout.addLayout(self.hbox_layout1)

        self.retranslateUi(StatusBar)
        QtCore.QMetaObject.connectSlotsByName(StatusBar)

    def retranslateUi(self, StatusBar):
        _translate = QtCore.QCoreApplication.translate
        StatusBar.setWindowTitle(_translate("StatusBar", "Form"))
